#!/usr/bin/env bash
set -euo pipefail

chromium="${BLUEPY_CHROMIUM_EXECUTABLE:-/run/current-system/sw/bin/chromium}"
args=(
  --disable-gpu
  --disable-dev-shm-usage
  --no-sandbox
)

if [[ "${BLUEPY_CHROMIUM_SINGLE_PROCESS:-1}" == "1" ]]; then
  args+=(--single-process)
fi

exec "$chromium" "${args[@]}" "$@"
